Limoee.Web.UI/Controllers/CompetitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Limoee.Application;
using Limoee.Application.CommandProcessor.Dispatcher;
using Limoee.Application.CompetitionResponseService;
using Limoee.Application.CompetitionResponseService;
using Limoee.Application.CompetitionService;

namespace Limoee.Web.UI.Controllers
{
    public class CompetitionController : Controller
    {
        private readonly ICommandBus _commandBus;
        private readonly ICompetitionQueryService _competitionQueryService;

        public CompetitionController(ICommandBus commandBus, ICompetitionQueryService competitionQueryService)
        {
            _commandBus = commandBus;
            _competitionQueryService = competitionQueryService;
        }


        /// <summary>
        /// لیست مسابقات 
        /// مسابقات جاری و فعال
        /// </summary>
        /// <returns></returns>
        public ActionResult List(int pageIndex = 1, int pageSize = 30)
        {
            var competition = _competitionQueryService.GetAllCompetitions(new PagingOptions(pageIndex, pageSize));
            return View(competition);
        }


        /// <summary>
        /// شرکت در مسابقه
        /// کاربر از لیست مسابقات موجود یکی را انتخاب کرده
        ///  و وارد صفحه ی مسابقه مربوطه شده و جواب سوالات مسابقه را ثبت می کند
        /// </summary>
        /// <returns></returns>
        public ActionResult Participate(Guid id)
        {
            var competition = _competitionQueryService.GetCompetition(id);
            var command = new CreateCompetitionResponseCommand()
            {
                UserName = "X",   // TODO Get the username 
                Competition = competition,
            };
            return View("Participate", command);
        }

        [HttpPost]
        public ActionResult Participate(CreateCompetitionResponseCommand command)
        {
            if (!ModelState.IsValid) return View("Participate");
            {
                var result = _commandBus.Submit(command);
                return Json(result);
            }
        }



    }
}

Limoee.Web.UI/Views/Competition/List.cshtml
@model Limoee.Infrastructure.Domain.PagedResult<Limoee.Application.CompetitionService.CompetitionDTO>

@{
    ViewBag.Title = "فهرست مسابقات";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>فهرست مسابقات</h2>


@foreach (var item in Model.Results)
{
    @item.Title
    <br />
    @Html.Raw(item.Description)
    <br />
    @item.StartDate
    <br />
    @item.EndDate
    <br />
    @Html.ActionLink("شرکت در مسابقه", "Participate", "Competition", new { id = item.Id }, null)
    <br/>
    <br/>
}
@Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalCount).Options(o => o.Action("Competitions").PageRouteValueKey("pageindex").AddRouteValue("pagesize", Model.PageSize).DisplayTemplate("Bootstrap3Pagination")
)

Limoee.Web.UI/Views/Competition/Participate.cshtml
@model Limoee.Application.CompetitionResponseService.CreateCompetitionResponseCommand

@{
    ViewBag.Title = "Participate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.UserName)
    @Html.HiddenFor(x => x.Competition.Id)

    <div>
        @Html.Label("عنوان مسابقه")
    </div>
    <div>
        @Html.DisplayTextFor(c => c.Competition.Title)
    </div>

    <div>
        @Html.Label("پرسشها")
    </div>

    <div>
        @for (var i = 0; i < Model.Competition.Questions.Count; i++)
        {
            @Html.DisplayTextFor(x => x.Competition.Questions[i].Title)

            foreach (var t in Model.Competition.Questions[i].Answers)
            {
                @Html.DisplayFor(c => t.Title)
                @Html.RadioButtonFor(x => x.Competition.Questions[i].Answers, t.Id)
                <br />
            }
        }
    </div>

    <div>
        <input type="submit" value="Submit" />
    </div>

}